services:
  postgres:
    image: postgres:18
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - 3500:5432
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data

volumes:
  backend_postgres_data:
