import { FirmTypeEnum, StepsEnum } from "@prisma/client";
import z from "zod";

const drawDownTexts = z.array(
  z.object({
    drawdown: z.string().optional(),
    englishText: z.string().optional(),
    arabicText: z.string().optional(),
  }),
);

const stringArray = () => z.array(z.string().min(1));

const createFirm = z.object({
  body: z
    .object({
      firmType: z.enum(FirmTypeEnum),
      title: z.string().min(1),
      dateEstablished: z.coerce.date().optional(),
      ceo: z.string().min(1).optional(),
      hidden: z.boolean().optional(),
      brokers: stringArray(),
      platforms: stringArray(),
      paymentMethods: stringArray(),
      payoutMethods: stringArray(),
      restrictedCountries: stringArray(),
      restrictedCountriesNote: z.string().optional(),
      restrictedCountriesNoteArabic: z.string().optional(),
      countries: stringArray(),
      typeOfInstruments: stringArray(),

      affiliateLink: z.string().min(1),
      maxAllocation: z.number().min(1),
      country: z.string().min(1),
      programTypes: z.array(z.enum(StepsEnum)),
      leverage: z.string().optional(),
      leverageArabic: z.string().optional(),
      commission: z.string().optional(),
      commissionArabic: z.string().optional(),
      drawDowns: stringArray().optional(),
      drawDownTexts: drawDownTexts.optional(),
      drawDownProgramTypeMap: z.record(z.string(), z.array(z.enum(StepsEnum))).optional(),
      otherFeatures: stringArray().optional(),
      challengeNames: z.array(z.object({
        id: z.string().optional(),
        name: z.string().min(1),
        nameArabic: z.string().optional().default(""),
        discountPercentage: z.number().min(0).max(100).optional().default(0),
        cnMaxAllocation: z.number().int().min(0).optional().default(0),
        cnNewsTrading: z.boolean().optional().default(false),
        cnOvernightWeekends: z.boolean().optional().default(false),
        cnCopyTrading: z.boolean().optional().default(false),
        cnExperts: z.boolean().optional().default(false),
        cnMinimumTradingDays: z.string().optional().default(""),
        cnMinimumTradingDaysArabic: z.string().optional().default(""),
      })).optional(),
      notes: z.string().optional(),
      notesArabic: z.string().optional(),

      accountSizes: z.string().optional(),
      accountSizesArabic: z.string().optional(),
      dailyMaxLoss: z.string().optional(),
      dailyMaxLossArabic: z.string().optional(),
      minimumTradingDays: z.string().optional(),
      minimumTradingDaysArabic: z.string().optional(),
      scaleupPlans: z.string().optional(),
      scaleupPlansArabic: z.string().optional(),

      payoutPolicy: z.string().optional(),
      consistencyRules: z.string().optional(),
      allocationRules: z.string().optional(),
      newsTradingAllowedRules: z.string().optional(),
      newsTradingNotAllowedRules: z.string().optional(),
      overnightAndWeekendsHolding: z.string().optional(),
      copyTradingAllowedRules: z.string().optional(),
      copyTradingNotAllowedRules: z.string().optional(),
      expertsAllowedRules: z.string().optional(),
      expertsNotAllowedRules: z.string().optional(),
      riskManagement: z.string().optional(),
      vpnVps: z.string().optional(),
      profitShare: z.string().optional(),
      inactivityRules: z.string().optional(),
      prohibitedStrategies: z.string().optional(),

      payoutPolicyArabic: z.string().optional(),
      consistencyRulesArabic: z.string().optional(),
      allocationRulesArabic: z.string().optional(),
      newsTradingAllowedRulesArabic: z.string().optional(),
      newsTradingNotAllowedRulesArabic: z.string().optional(),
      overnightAndWeekendsHoldingArabic: z.string().optional(),
      copyTradingAllowedRulesArabic: z.string().optional(),
      copyTradingNotAllowedRulesArabic: z.string().optional(),
      expertsAllowedRulesArabic: z.string().optional(),
      expertsNotAllowedRulesArabic: z.string().optional(),
      riskManagementArabic: z.string().optional(),
      vpnVpsArabic: z.string().optional(),
      profitShareArabic: z.string().optional(),
      inactivityRulesArabic: z.string().optional(),
      prohibitedStrategiesArabic: z.string().optional(),

      leverageMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      commissionMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      accountSizesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      allocationRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      dailyMaxLossMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      riskManagementMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      consistencyRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      minimumTradingDaysMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      newsTradingAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      newsTradingNotAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      overnightAndWeekendsHoldingMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      copyTradingAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      copyTradingNotAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      expertsAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      expertsNotAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      vpnVpsMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      profitShareMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      payoutPolicyMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      scaleupPlansMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      inactivityRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      prohibitedStrategiesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      restrictedCountriesNoteMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
    })
    .strict(),
});

const updateFirm = z.object({
  params: z.object({
    firmId: z.string().min(1),
  }),
  body: z
    .object({
      title: z.string().min(1).optional(),
      dateEstablished: z.coerce.date().optional(),
      ceo: z.string().min(1).optional(),
      hidden: z.boolean().optional(),
      brokers: stringArray().optional(),
      platforms: stringArray().optional(),
      paymentMethods: stringArray().optional(),
      payoutMethods: stringArray().optional(),
      restrictedCountries: stringArray().optional(),
      restrictedCountriesNote: z.string().optional(),
      restrictedCountriesNoteArabic: z.string().optional(),
      countries: stringArray().optional(),
      typeOfInstruments: stringArray().optional(),
      payoutPolicy: z.string(),
      drawDowns: stringArray().optional(),
      drawDownTexts: drawDownTexts.optional(),
      drawDownProgramTypeMap: z.record(z.string(), z.array(z.enum(StepsEnum))).optional(),
      otherFeatures: stringArray().optional(),
      challengeNames: z.array(z.object({
        id: z.string().optional(),
        name: z.string().min(1),
        nameArabic: z.string().optional().default(""),
        discountPercentage: z.number().min(0).max(100).optional().default(0),
        cnMaxAllocation: z.number().int().min(0).optional().default(0),
        cnNewsTrading: z.boolean().optional().default(false),
        cnOvernightWeekends: z.boolean().optional().default(false),
        cnCopyTrading: z.boolean().optional().default(false),
        cnExperts: z.boolean().optional().default(false),
        cnMinimumTradingDays: z.string().optional().default(""),
        cnMinimumTradingDaysArabic: z.string().optional().default(""),
      })).optional(),
      leverage: z.string().optional(),
      leverageArabic: z.string().optional(),
      commission: z.string().optional(),
      commissionArabic: z.string().optional(),
      consistencyRules: z.string(),
      affiliateLink: z.string().min(1).optional(),
      maxAllocation: z.number().min(1).optional(),
      country: z.string().min(1).optional(),
      programTypes: z.array(z.enum(StepsEnum)).optional(),
      notes: z.string().optional(),
      notesArabic: z.string().optional(),

      accountSizes: z.string().optional(),
      accountSizesArabic: z.string().optional(),
      dailyMaxLoss: z.string().optional(),
      dailyMaxLossArabic: z.string().optional(),
      minimumTradingDays: z.string().optional(),
      minimumTradingDaysArabic: z.string().optional(),
      scaleupPlans: z.string().optional(),
      scaleupPlansArabic: z.string().optional(),
      allocationRules: z.string().optional(),
      newsTradingAllowedRules: z.string().optional(),
      newsTradingNotAllowedRules: z.string().optional(),
      overnightAndWeekendsHolding: z.string().optional(),
      copyTradingAllowedRules: z.string().optional(),
      copyTradingNotAllowedRules: z.string().optional(),
      expertsAllowedRules: z.string().optional(),
      expertsNotAllowedRules: z.string().optional(),
      riskManagement: z.string().optional(),
      vpnVps: z.string().optional(),
      profitShare: z.string().optional(),
      inactivityRules: z.string().optional(),
      prohibitedStrategies: z.string().optional(),

      payoutPolicyArabic: z.string().optional(),
      consistencyRulesArabic: z.string().optional(),
      allocationRulesArabic: z.string().optional(),
      newsTradingAllowedRulesArabic: z.string().optional(),
      newsTradingNotAllowedRulesArabic: z.string().optional(),
      overnightAndWeekendsHoldingArabic: z.string().optional(),
      copyTradingAllowedRulesArabic: z.string().optional(),
      copyTradingNotAllowedRulesArabic: z.string().optional(),
      expertsAllowedRulesArabic: z.string().optional(),
      expertsNotAllowedRulesArabic: z.string().optional(),
      riskManagementArabic: z.string().optional(),
      vpnVpsArabic: z.string().optional(),
      profitShareArabic: z.string().optional(),
      inactivityRulesArabic: z.string().optional(),
      prohibitedStrategiesArabic: z.string().optional(),

      leverageMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      commissionMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      accountSizesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      allocationRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      dailyMaxLossMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      riskManagementMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      consistencyRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      minimumTradingDaysMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      newsTradingAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      newsTradingNotAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      overnightAndWeekendsHoldingMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      copyTradingAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      copyTradingNotAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      expertsAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      expertsNotAllowedRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      vpnVpsMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      profitShareMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      payoutPolicyMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      scaleupPlansMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      inactivityRulesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      prohibitedStrategiesMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
      restrictedCountriesNoteMobileFontSize: z.number().int().min(10).max(24).optional().nullable(),
    })
    .strict(),
});

const deleteFirm = z.object({
  body: z
    .object({
      id: z.string(),
    })
    .strict(),
});

export const FirmValidation = {
  createFirm,
  updateFirm,
  deleteFirm,
};

export type CreateFirm = z.infer<typeof createFirm>;
export type UpdateFirm = z.infer<typeof updateFirm>;
export type DeleteFirm = z.infer<typeof deleteFirm>;
